package com.lotato.pro.models;

public class Bet {
    private String id;
    private String game;
    private String number;
    private String cleanNumber;
    private double amount;
    private String drawId;
    private String drawName;
    private boolean free;
    private String freeType;
    private boolean isAutoGenerated;
    private String specialType;
    private int option;

    public Bet() {}

    public Bet(String game, String number, String cleanNumber, double amount, String drawId, String drawName) {
        this.id = String.valueOf(System.currentTimeMillis() + Math.random());
        this.game = game;
        this.number = number;
        this.cleanNumber = cleanNumber;
        this.amount = amount;
        this.drawId = drawId;
        this.drawName = drawName;
        this.free = false;
    }

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    public String getGame() { return game; }
    public void setGame(String game) { this.game = game; }
    public String getNumber() { return number; }
    public void setNumber(String number) { this.number = number; }
    public String getCleanNumber() { return cleanNumber; }
    public void setCleanNumber(String cleanNumber) { this.cleanNumber = cleanNumber; }
    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }
    public String getDrawId() { return drawId; }
    public void setDrawId(String drawId) { this.drawId = drawId; }
    public String getDrawName() { return drawName; }
    public void setDrawName(String drawName) { this.drawName = drawName; }
    public boolean isFree() { return free; }
    public void setFree(boolean free) { this.free = free; }
    public String getFreeType() { return freeType; }
    public void setFreeType(String freeType) { this.freeType = freeType; }
    public boolean isAutoGenerated() { return isAutoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { isAutoGenerated = autoGenerated; }
    public String getSpecialType() { return specialType; }
    public void setSpecialType(String specialType) { this.specialType = specialType; }
    public int getOption() { return option; }
    public void setOption(int option) { this.option = option; }

    public String getGameAbbreviation() {
        if (specialType != null && !specialType.isEmpty()) return specialType;
        switch (game) {
            case "borlette": return "B";
            case "lotto3": return "L3";
            case "lotto4": return "L4";
            case "lotto5": return "L5";
            case "mariage": return "M";
            case "auto_marriage": return "AM";
            case "auto_lotto4": return "AL4";
            case "auto_lotto5": return "AL5";
            default: return game.toUpperCase();
        }
    }
}
